"""Generates an audit-grade compliance report for the demo scenario.

Runs the five checks a regulated buyer / auditor cares about and emits a markdown
report. Each check returns (name, passed, detail).
"""
from __future__ import annotations

def _provenance_complete(db, mem_id) -> bool:
    meta = db.store.get_meta(mem_id)
    if not meta:
        return False
    return bool(meta["signature_valid"]) and bool(meta["source"])


def run_compliance_audit(db, ids, nurse_res, intern_res, nurse, intern, dpo) -> tuple[list, str]:
    checks = []

    # 1. Provenance coverage: every recalled+cited memory traces to a signed source
    cited_ids = {c["id"] for c in nurse_res["cited"]} | {c["id"] for c in intern_res["cited"]}
    answer_ids = {nurse_res["answer_id"], intern_res["answer_id"]}
    audited = cited_ids | answer_ids
    complete = [m for m in audited if _provenance_complete(db, m)]
    cov = len(complete) / len(audited) if audited else 1.0
    checks.append(("Provenance coverage", cov == 1.0,
                   f"{len(complete)}/{len(audited)} recalled+answer memories trace to a "
                   f"signed source ({cov:.0%})"))

    # 2. Zero permission bypass — CONTENT level (not just id): the restricted
    #    clinical fact must never reach the intern, directly OR via a derived memory.
    SECRET = "atrial fibrillation"
    probe = db.recall("atrial fibrillation anticoagulant warfarin clinical note",
                      principal=intern, k=20)
    intern_seen = intern_res["recalled"] + probe["results"]
    id_leak = any(r["id"] == ids["JANE_DX"] for r in intern_seen)
    content_leak = any(SECRET in (r.get("content") or "") for r in intern_seen)
    leaked = id_leak or content_leak
    checks.append(("Zero permission bypass (content-level)", not leaked,
                   f"restricted clinical fact never reaches intern — direct id leak={id_leak}, "
                   f"derived/content leak={content_leak} (high-water-mark label inheritance)"))

    # 3. Audit chain integrity
    chain_ok = db.verify_audit()
    n_events = sum(1 for _ in db.store.iter_audit())
    checks.append(("Audit chain integrity", chain_ok,
                   f"hash-chain verified over {n_events} events (tamper-evident)"))

    # 4. Right-to-erasure (GDPR Art.17): crypto-shred a subject, verify + isolation
    rcpt = db.forget("member:jane", mode="hard", actor=dpo.id, reason="DSAR",
                     legal_basis="GDPR Art.17")
    post = db.recall("Jane Doe emergency room claim atrial fibrillation", principal=nurse, k=20)
    jane_leak = any((db.store.get_meta(r["id"]) or {}).get("subject") == "member:jane"
                    for r in post["results"])
    # content-level: the clinical fact must be gone even from DERIVED memories
    residue = any(SECRET in (r.get("content") or "") for r in post["results"])
    bob = db.recall("Bob Stone Silver HMO member", principal=nurse, k=20)
    bob_ok = any((db.store.get_meta(r["id"]) or {}).get("subject") == "member:bob"
                 for r in bob["results"])
    _, state = db.store.get_key(db.tenant, "member:jane")
    erase_event = any(a == "forget" and t == "member:jane"
                      for a, t in ((e["action"], e["target"]) for e in db.store.iter_audit()))
    erased_ok = (not jane_leak) and (not residue) and bob_ok and state == "shredded" and erase_event
    checks.append(("Right-to-erasure (GDPR Art.17)", erased_ok,
                   f"purged={rcpt['purged']} (incl. {rcpt['cascade']} derived via lineage cascade), "
                   f"DEK={state}, post-erasure jane-recall=0, residual clinical content={residue}, "
                   f"other member (bob) intact={bob_ok}, erasure event retained={erase_event}"))

    # 5. Read-your-writes (index freshness)
    fresh = nurse_res["index_lag"] == 0 and intern_res["index_lag"] == 0 and \
        db.flush_index()["index_lag"] == 0
    checks.append(("Read-your-writes (freshness)", fresh,
                   "index_lag=0 at recall time and after flush (synchronous indexing)"))

    return checks, _render(db, ids, nurse_res, intern_res, checks)


def _render(db, ids, nurse_res, intern_res, checks) -> str:
    passed = sum(1 for _, ok, _ in checks)
    out = []
    out.append("# Heartwood — Compliance Audit Report")
    out.append("")
    out.append(f"_Generated by the regulated-support demo. Engine: {db.info()}_")
    out.append("")
    out.append("**Scenario:** health-plan member-support agent over a governed knowledge base "
               "(policies + member PII + a restricted clinical record).")
    out.append("")
    out.append("## Same ticket, two clearances — governed answers")
    out.append("")
    for res, note in ((nurse_res, "clinical role + restricted clearance"),
                      (intern_res, "support role + confidential clearance")):
        out.append(f"### {res['principal']} ({note})")
        out.append(f"- recalled {len(res['recalled'])} memories; cited {len(res['cited'])}; "
                   f"restricted records used: {len(res['restricted_used'])}")
        out.append("```")
        out.append(res["answer_text"])
        out.append("```")
        out.append("")
    out.append("> The intern's answer is missing the clinical record entirely — it was never a "
               "retrieval candidate for that principal. Existence is not leaked via count, score, "
               "or latency.")
    out.append("")
    out.append("## Compliance checks")
    out.append("")
    out.append("| # | Check | Result | Evidence |")
    out.append("|---|-------|--------|----------|")
    for i, (name, ok, detail) in enumerate(checks, 1):
        out.append(f"| {i} | {name} | {'✅ PASS' if ok else '❌ FAIL'} | {detail} |")
    out.append("")
    out.append(f"## Result: {passed}/{len(checks)} checks passed — "
               f"{'audit-ready' if passed == len(checks) else 'NOT audit-ready'}.")
    out.append("")
    out.append("_What no current agent-memory framework provides: every answer source-attributed, "
               "restricted data access-governed in the retrieval path, tamper-evident audit, and "
               "verifiable crypto-shred erasure of derived data (embeddings included)._")
    return "\n".join(out)
