"""Capability contracts and signed rotation measured diffs.

This package contains schemas, validation, privileged contract storage, and
signing/audit wiring only. It does not invoke models or import provider SDKs.
"""
from .schema import (
    CONTRACT_SCHEMA_VERSION,
    RECEIPT_SCHEMA_VERSION,
    RECEIPT_SIGNING_VERSION,
    BaselineBinding,
    CapabilityContract,
    ContinuityValidationError,
    ContractBinding,
    DeclarativeFallback,
    ErrorCategory,
    EvalSuiteBinding,
    EvidenceMode,
    FallbackObservation,
    FallbackPolicy,
    FallbackPolicyName,
    FallbackTrigger,
    LatencyClass,
    Outcome,
    PriceClass,
    RotationCase,
    RotationReceiptDraft,
    RotationSummary,
    SignedRotationReceipt,
    StructuredOutput,
    canonical_json,
    content_hash,
    sanitize_error_category,
)
from .service import (
    CONTINUITY_ADMIN_ROLE,
    CONTINUITY_CONTRACT_KIND,
    CONTINUITY_POLICY_SCOPE,
    Continuity,
    ContinuityIntegrityError,
    StoredCapabilityContract,
)

__all__ = [
    "CONTRACT_SCHEMA_VERSION",
    "RECEIPT_SCHEMA_VERSION",
    "RECEIPT_SIGNING_VERSION",
    "CONTINUITY_ADMIN_ROLE",
    "CONTINUITY_CONTRACT_KIND",
    "CONTINUITY_POLICY_SCOPE",
    "CapabilityContract",
    "StructuredOutput",
    "DeclarativeFallback",
    "FallbackPolicy",
    "FallbackPolicyName",
    "LatencyClass",
    "PriceClass",
    "ContractBinding",
    "EvalSuiteBinding",
    "BaselineBinding",
    "RotationCase",
    "FallbackObservation",
    "FallbackTrigger",
    "RotationSummary",
    "RotationReceiptDraft",
    "SignedRotationReceipt",
    "Outcome",
    "ErrorCategory",
    "EvidenceMode",
    "ContinuityValidationError",
    "ContinuityIntegrityError",
    "StoredCapabilityContract",
    "Continuity",
    "canonical_json",
    "content_hash",
    "sanitize_error_category",
]
